// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

error ZeroAddress();
error InsufficientGas();
error NotInDistributionWindow();
error AlreadyDistributedToday();
error EmptyPool();
error NoReceivers();
error TooManyReceivers();
error AmountTooLow();
error AmountTooHigh();
error ValueMismatch();
error AlreadyInReceiverPool();
error ContributedToday();
error NoFailedTransfer();
error NotDistributor();
error TooManyActions();
error TooManyTransactions();
error DistributionFailed();
error NotSystem();
error EmptyName();
error NameTooLong();
error TransferFailedErr();
error TooEarlyToRetry();
error MaxRetriesExceeded();
error EmergencyWithdrawalFailed();
error NotAdmin();
error InsufficientContractBalance();
error PoolBalanceBelowMinimum();
error DailyContributionLimitExceeded();
error DailyReceiverEntryLimitExceeded();
